# Generated by Django 4.2.4 on 2023-08-23 13:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('about_short', ckeditor.fields.RichTextField()),
                ('about', ckeditor.fields.RichTextField()),
                ('Vision', ckeditor.fields.RichTextField()),
                ('Mission', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
