# Generated by Django 4.2.4 on 2023-08-23 15:04

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_aboutsteps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsteps',
            name='Mission',
        ),
        migrations.RemoveField(
            model_name='aboutsteps',
            name='Vision',
        ),
        migrations.CreateModel(
            name='VisionSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vision', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('visionsec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vision_steps', to='products.about')),
            ],
        ),
        migrations.CreateModel(
            name='MissionSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mission', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('missionsec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_steps', to='products.about')),
            ],
        ),
    ]
