# Generated by Django 4.2.4 on 2023-08-27 16:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_aboutsteps_mission_remove_aboutsteps_vision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('products_description', ckeditor.fields.RichTextField()),
                ('products_features', ckeditor.fields.RichTextField()),
                ('product_videolink', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
