# Generated by Django 4.2.4 on 2023-08-27 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_about_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagesabout', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_images', to='products.about')),
            ],
        ),
    ]
