# Generated by Django 4.2.4 on 2023-08-31 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_multipleimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultipleImages',
        ),
    ]
