# Generated by Django 4.2.4 on 2023-09-01 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_delete_multipleimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsteps',
            name='aboutsec',
        ),
        migrations.RemoveField(
            model_name='missionsteps',
            name='missionsec',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.RemoveField(
            model_name='visionsteps',
            name='visionsec',
        ),
        migrations.DeleteModel(
            name='AboutSteps',
        ),
        migrations.DeleteModel(
            name='MissionSteps',
        ),
        migrations.DeleteModel(
            name='VisionSteps',
        ),
    ]
