# Generated by Django 4.2.4 on 2023-09-01 08:26

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_aboutsteps_aboutsec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='Mission',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='Vision',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='about',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_short',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
