# Generated by Django 4.2.4 on 2023-09-01 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_about_mission_alter_about_vision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='images',
        ),
    ]
