# Generated by Django 4.2.4 on 2023-09-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productcategory_product_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
