# Generated by Django 4.2.4 on 2023-09-06 14:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_short',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
    ]
