# Generated by Django 4.2.4 on 2023-09-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='founder',
            name='fname_slug',
            field=models.SlugField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='name_slug',
            field=models.SlugField(blank=True, default=None, null=True, unique=True),
        ),
    ]
